name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    # 사용할 Secret의 프로비저닝 프로파일을 env에 설정
    env:
      PROFILE_APPSTORE: ${{ secrets.PROFILE_APPSTORE_BASE64 }}
      PROFILE_ADHOC: ${{ secrets.PROFILE_ADHOC_BASE64 }}
      # PROFILE_...: ${{ secrets.... }}

    steps:
      ##############################################################
      # 1. 소스체크아웃
      ##############################################################
      - name: Checkout
        uses: actions/checkout@v4


      ##############################################################
      # 2. 환경변수
      # 2-1. iOS프로젝트 경로 찾기
      ##############################################################
      - name: Locate ios project directory
        run: |
          ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'
          echo "IOS_PROJECT_PATH=$(dirname $(find . -maxdepth 5 -name '*.xcodeproj' | head -n 1))" >> $GITHUB_ENV


      ##############################################################
      # 2-2. Scheme & project 값 추출
      ##############################################################    
      - name: Set Default iOS Project Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo Using scheme: $scheme
          echo "SCHEME=$scheme" >> $GITHUB_ENV
   
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          echo Using file_to_build: $file_to_build
          echo Using file_type: $filetype_parameter
          echo "FILE_TYPE=$filetype_parameter" >> $GITHUB_ENV
          echo "FILE_TO_BUILD=$file_to_build" >> $GITHUB_ENV

        working-directory: ${{ env.IOS_PROJECT_PATH }}


      ##############################################################
      # 2-3. CocoaPods 의존성 설치 (Podfile이 있을 경우)
      ##############################################################
      # - name: Install CocoaPods Dependencies
      #   run: pod install
      #   working-directory: ${{ env.IOS_PROJECT_PATH }}




      ##############################################################
      # 3. 환경 구축
      # 3-1 키체인 초기화 - 임시 키체인 생성
      ##############################################################    
      - name: Configure Keychain 
        run: |
          echo "Creating build keychain..."
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain


      ##############################################################
      # 3-2. 인증서 설치
      ##############################################################    
      - name: Import Certificate
        run: |
          echo "Decoding certificate from Secrets..."
          echo "${{ secrets.CERTIFICATE_BASE64 }}" | base64 --decode > certificate.p12

          echo "Importing certificate..."
          security import certificate.p12 -k build.keychain -P "" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain


      ##############################################################
      # 3-3. 프로비저닝 프로파일 설치
      ##############################################################
      - name: Install Provisioning Profile
        run: |
          echo "Installing provisioning profile..."
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

          echo "PROFILE* 환경변수 목록 추출"
          for var in $(printenv | grep '^PROFILE' | cut -d= -f1); do
            echo "• Processing.. : $var"
            echo "${!var}" | base64 --decode > temp.mobileprovision
            security cms -D -i temp.mobileprovision -o temp.plist
            uuid=$(/usr/libexec/PlistBuddy -c 'Print :UUID' temp.plist)
            echo "  → profile UUID: $uuid"
            cp temp.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$uuid.mobileprovision
            rm temp.mobileprovision temp.plist
          done




      # ##############################################################
      # # 4. 앱 빌드
      # # 4-1 디버깅 빌드
      # ##############################################################    
      # - name: Build
      #   run: |
      #     echo "build Target Scheme: $SCHEME"
      #     echo "build Target File: $FILE_TO_BUILD"

      #     xcodebuild clean build \
      #       -${FILE_TYPE} "$FILE_TO_BUILD" \
      #       -scheme "$SCHEME" \
      #       -configuration Debug

      #   working-directory: ${{ env.IOS_PROJECT_PATH }}



      ##############################################################
      # 4-2. UI Test 진행
      ##############################################################    
      # - name: Run UI tests
      #   run: |
      #     SIMULATOR=$(
      #       xcrun simctl list devices available \
      #         | grep -E 'iPhone [0-9]+' \
      #         | sed -E 's/.*(iPhone [0-9]+).*$/\1/' \
      #         | sort -Vu \
      #         | tail -n1
      #     )
      #     xcodebuild test \
      #       -${FILE_TYPE} "$FILE_TO_BUILD" \
      #       -scheme "$SCHEME" \
      #       -destination "platform=iOS Simulator,name=${SIMULATOR},OS=latest"

      #   working-directory: ${{ env.IOS_PROJECT_PATH }}



      ##############################################################
      # 4-3. release 아카이브
      ##############################################################    
      - name: Archive
        run: |
          xcodebuild clean archive \
            -${FILE_TYPE} "$FILE_TO_BUILD" \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "./build/$SCHEME.xcarchive"
            
        working-directory: ${{ env.IOS_PROJECT_PATH }}



      ##############################################################
      # 4-4. IPA파일 생성
      ##############################################################    
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath "./build/$SCHEME.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "./build" 

        working-directory: ${{ env.IOS_PROJECT_PATH }}


      ##############################################################
      # 4-4. IPA파일 생성
      ##############################################################    
      - name: Export IPA
        run: |
          mkdir private_keys
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}" > private_keys/AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8

          xcrun altool --upload-app \
          --file "${{ env.IOS_PROJECT_PATH }}/build/${{ env.SCHEME }}.ipa" \
          --apiKey "${{ secrets.APPSTORE_KEY_ID }}" \
          --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}" \
          --verbose 

        working-directory: ${{ env.IOS_PROJECT_PATH }}
        


      ##############################################################
      # 5. artifact 생성
      ##############################################################    
      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SCHEME }}.ipa
          path: build/${{ env.SCHEME }}.ipa



