name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      ##############################################################
      # 1. 소스체크아웃
      ##############################################################
      - name: Checkout
        uses: actions/checkout@v4


      ##############################################################
      # 1-2. CocoaPods 의존성 설치 (Podfile이 있을 경우)
      ##############################################################
      # - name: Install CocoaPods Dependencies
      #   run: pod install


      ##############################################################
      # 2. Scheme 값 추출
      ##############################################################    
      - name: Set Default Scheme
        run: |
          ls
          cd mtest/native/ios/project
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      ##############################################################
      # 3. 환경 구축
      # 3-1 키체인 초기화 - 임시 키체인 생성
      ##############################################################    
      - name: Configure Keychain 
        run: |
          echo "Creating build keychain..."
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain

      ##############################################################
      # 3-2. 인증서 설치
      ##############################################################    
      - name: Import Certificate
        run: |
          echo "Decoding certificate from Secrets..."
          echo "${{ secrets.CERTIFICATE_BASE64 }}" | base64 --decode > certificate.p12

          echo "Importing certificate..."
          security import certificate.p12 -k build.keychain -P ""


      ##############################################################
      # 3-3. 프로비저닝 프로파일 설치
      ##############################################################
      - name: Install Provisioning Profile
        run: |
          echo "Installing provisioning profile..."
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.PROFILE_ADHOC_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Adhoc.mobileprovision
          echo "${{ secrets.PROFILE_APPSTORE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Appstore.mobileprovision


      ##############################################################
      # 4. 앱 빌드
      ##############################################################    
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          ls
          cd mtest/native/ios/project
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild clean build analyze -scheme "$scheme" -configuration Debug
